######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 1 15:29:07 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += widget.cpp
