######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 1 15:21:14 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quit_button.cpp
