######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 1 15:12:58 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += color_label.cpp hello_label.cpp main.cpp
